<a href="https://colab.research.google.com/github/Zeus-csu/ds_practicum/blob/main/first_nb.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
import numpy as np



In [29]:
ar1 = np.arange(1,20,3)
#short_arr = ar1[5:]
 short_arr = ar1[5:].copy()
short_arr[:] = 0
short_arr


array([0, 0])

In [51]:
ar1

array([ 1,  4,  7, 10, 13, 16, 19])

In [10]:

sliced_arr = arr[2:2]
sliced_arr

array([], shape=(0, 3), dtype=int64)

In [40]:
arr = np.array([[1,2,3],[4,5,6],[7,8,9]])
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [52]:
#arr[1:3,1:3]
arr[:2,1:]

array([[2, 3],
       [5, 6]])

In [53]:
# 3D array
arr3d = np.array([[[ 0,  1,  2],
                   [ 3,  4,  5],
                   [ 6,  7,  8]],

                  [[ 9, 10, 11],
                   [12, 13, 14],
                   [15, 16, 17]],

                  [[18, 19, 20],
                   [21, 22, 23],
                   [24, 25, 26]]])
arr3d

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [63]:
#arr3d[1][2,1]
#arr3d[2][1,:]
#arr3d[0][2,1]
arr3d[0][1:3,1:6]

array([[4, 5],
       [7, 8]])

In [85]:
names =np.array(['Ali','Vali',"G'ani",'Olim','Vali'])
names

array(['Ali', 'Vali', "G'ani", 'Olim', 'Vali'], dtype='<U5')

In [76]:
infos = np.random.randn(5,4)
infos

array([[ 1.56373631,  0.41215175,  0.04011347, -0.83918221],
       [ 0.38444058, -1.30622653,  0.30067406, -0.32849543],
       [ 0.60811528,  0.60280097, -1.22714202, -0.98095484],
       [ 0.2382645 ,  0.97404626, -0.27280464,  1.42643045],
       [-0.66136476, -0.81970704,  0.5942308 , -1.10284845]])

In [100]:
names == 'Vali'

infos[(names == 'Ali') | (names == 'Vali')  ,:2]


array([[ 1.56373631,  0.41215175],
       [ 0.38444058, -1.30622653],
       [-0.66136476, -0.81970704]])

In [102]:
#infos[names != 'Ali',:]
infos[~(names== 'Ali')]

array([[ 0.38444058, -1.30622653,  0.30067406, -0.32849543],
       [ 0.60811528,  0.60280097, -1.22714202, -0.98095484],
       [ 0.2382645 ,  0.97404626, -0.27280464,  1.42643045],
       [-0.66136476, -0.81970704,  0.5942308 , -1.10284845]])

In [99]:
mask = (names == 'Ali') | (names=='Olim')
infos[mask]

array([[ 1.56373631,  0.41215175,  0.04011347, -0.83918221],
       [ 0.2382645 ,  0.97404626, -0.27280464,  1.42643045]])

In [104]:
infos[infos<0]=0
infos
infos[mask]

array([[1.56373631, 0.41215175, 0.04011347, 0.        ],
       [0.2382645 , 0.97404626, 0.        , 1.42643045]])